language: php
php:
 - '7.0'
services:
 - mysql
before_install:
 - cd src
 - mysql -e 'CREATE DATABASE laravel_test;'
 - php artisan migrate
install: composer install
script: vendor/bin/codecept run
env:
 - DB_CONNECTION=mysql DB_HOST=127.0.0.1 DB_PORT=3306 DB_DATABASE=laravel_test DB_USERNAME=root DB_PASSWORD=