language: php
php:
 - '7.0'
services:
 - mysql
before_install:
 - cd src
 - cp .env.ci .env.testing
 - mysql -e 'CREATE DATABASE laravel_test;'
install:
 - composer install
script: vendor/bin/codecept run