web:
  image: nginx:latest
  container_name: web_server
  ports:
      - "80:80"
  volumes:
      - ./src:/src
      - ./docker/config/site.conf:/etc/nginx/conf.d/site.conf
  links:
    - app
    
app:
  build: .
  container_name: app
  volumes:
    - ./src:/src
  links:
    - db

db:
  image: mysql:latest
  container_name: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=root
    - MYSQL_PASSWORD=root
    - MYSQL_DATABASE=laravel