web:
  image: nginx:latest
  container_name: web
  ports:
      - "80:80"
  volumes:
      - ./src:/src
      - ./docker/config/site.conf:/etc/nginx/conf.d/site.conf
  links:
    - php
    
php:
  build: .
  container_name: php
  volumes:
    - ./src:/src
  links:
    - mysql

mysql:
  image: mysql:latest
  container_name: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=root
    - MYSQL_PASSWORD=root
    - MYSQL_DATABASE=laravel